In [1]:
import pandas as pd
from sklearn.naive_bayes import BernoulliNB
import numpy as np

In [2]:
tel = pd.read_csv(r"C:\Training\Academy\Statistics (Python)\Datasets\tel_bayes.csv")
tel

TT_gt_100  Gender    Response
0         y    male  not bought
1         n    male  not bought
2         n  female  not bought
3         n  female  not bought
4         n    male  not bought
5         n    male  not bought
6         y    male      bought
7         y  female      bought
8         n  female      bought
9         y  female      bought

In [3]:
dum_tel = pd.get_dummies(tel, drop_first=True)
dum_tel

TT_gt_100_y  Gender_male  Response_not bought
0            1            1                    1
1            0            1                    1
2            0            0                    1
3            0            0                    1
4            0            1                    1
5            0            1                    1
6            1            1                    0
7            1            0                    0
8            0            0                    0
9            1            0                    0

In [4]:
nb = BernoulliNB(alpha=0, force_alpha=True)
X = dum_tel[['TT_gt_100_y' , 'Gender_male']]
y = dum_tel['Response_not bought']

In [5]:
nb.fit(X, y) # Calculates apriori probs

BernoulliNB(alpha=0, force_alpha=True)

In [6]:
tst = np.array([["n","female"],
                ["n","male"],
                ["y","male"],
                ["y", "female"]])
tst = pd.DataFrame(tst, columns = ['TT_gt_100',
                                   'Gender'])
tst

TT_gt_100  Gender
0         n  female
1         n    male
2         y    male
3         y  female

In [7]:
dum_tst = pd.get_dummies(tst, drop_first=True)
dum_tst

TT_gt_100_y  Gender_male
0            0            0
1            0            1
2            1            1
3            1            0

In [8]:
nb.predict_proba(dum_tst)

array([[0.31034483, 0.68965517],
       [0.06976744, 0.93023256],
       [0.52941176, 0.47058824],
       [0.87096774, 0.12903226]])

`.predict()` gives the indices of high probabilities

In [9]:
nb.predict(dum_tst)

array([1, 1, 0, 0], dtype=uint8)

In [10]:
np.argmax([[0.31034483, 0.68965517],
       [0.06976744, 0.93023256],
       [0.52941176, 0.47058824],
       [0.87096774, 0.12903226]], axis=1)

array([1, 1, 0, 0], dtype=int64)